select
    COMTCADMINISTCODE.ADMINIST_ZONE_SE /* 青沥内靛.青沥备开备盒 */
    , COMTCADMINISTCODE.ADMINIST_ZONE_CODE /* 青沥内靛.青沥备开内靛 */
    , COMTCADMINISTCODE.USE_AT /* 青沥内靛.荤侩咯何 */
    , COMTCADMINISTCODE.ADMINIST_ZONE_NM /* 青沥内靛.青沥备开疙 */
    , COMTCADMINISTCODE.UPPER_ADMINIST_ZONE_CODE /* 青沥内靛.惑困青沥备开内靛 */
--    , decode(COMTCADMINISTCODE.ADMINIST_ZONE_CODE, '__00000000', COMTCADMINISTCODE.ADMINIST_ZONE_CODE) as UPPER_ADMINIST_ZONE_CODE_01 /* 青沥内靛.青沥备开内靛 */
    , case when COMTCADMINISTCODE.ADMINIST_ZONE_CODE like '__00000000' then '0000000000'
    when COMTCADMINISTCODE.ADMINIST_ZONE_CODE like '_____00000' then substr(COMTCADMINISTCODE.ADMINIST_ZONE_CODE, 1, 2) || '00000000'
    when COMTCADMINISTCODE.ADMINIST_ZONE_CODE like '________00' then substr(COMTCADMINISTCODE.ADMINIST_ZONE_CODE, 1, 8) || '00'
--    when COMTCADMINISTCODE.ADMINIST_ZONE_CODE like '__________' then substr(COMTCADMINISTCODE.ADMINIST_ZONE_CODE, 1)
    else COMTCADMINISTCODE.ADMINIST_ZONE_CODE
    end as UPPER_ADMINIST_ZONE_CODE_01 /* 青沥内靛.青沥备开内靛 */
    , COMTCADMINISTCODE.CREAT_DE /* 青沥内靛.积己老 */
    , COMTCADMINISTCODE.ABL_DE /* 青沥内靛.企瘤老 */
    , COMTCADMINISTCODE.FRST_REGIST_PNTTM /* 青沥内靛.弥檬殿废矫痢 */
    , COMTCADMINISTCODE.FRST_REGISTER_ID /* 青沥内靛.弥檬殿废磊ID */
    , COMTCADMINISTCODE.LAST_UPDT_PNTTM /* 青沥内靛.弥辆荐沥矫痢 */
    , COMTCADMINISTCODE.LAST_UPDUSR_ID /* 青沥内靛.弥辆荐沥磊ID */
from COMTCADMINISTCODE /* 青沥内靛 */
where 1 = 1
--    and COMTCADMINISTCODE.ADMINIST_ZONE_SE = '1' /* 青沥内靛.青沥备开备盒 = 过沥悼 */
--    and COMTCADMINISTCODE.ADMINIST_ZONE_CODE like '__00000000' /* 青沥内靛.青沥备开内靛 矫档 2 */
----    and COMTCADMINISTCODE.ADMINIST_ZONE_CODE like '____000000' /* 青沥内靛.青沥备开内靛 矫焙备 3 */
----    and COMTCADMINISTCODE.ADMINIST_ZONE_CODE like '_______000' /* 青沥内靛.青沥备开内靛 谰搁悼 3 */
----    and COMTCADMINISTCODE.ADMINIST_ZONE_CODE like '__________' /* 青沥内靛.青沥备开内靛 府 2*/
--    and COMTCADMINISTCODE.USE_AT = 'Y' /* 青沥内靛.荤侩咯何 */
--    and COMTCADMINISTCODE.ADMINIST_ZONE_CODE like '11___00000' /* 青沥内靛.青沥备开内靛 矫档 2 */
    and UPPER_ADMINIST_ZONE_CODE = '1100000000'
order by
    COMTCADMINISTCODE.ADMINIST_ZONE_CODE /* 青沥内靛.青沥备开内靛 */
;

select
    a.UPPER_ADMINIST_ZONE_CODE_01
    , (select COMTCADMINISTCODE.ADMINIST_ZONE_NM from COMTCADMINISTCODE where COMTCADMINISTCODE.ADMINIST_ZONE_SE = a.ADMINIST_ZONE_SE and COMTCADMINISTCODE.ADMINIST_ZONE_CODE = a.UPPER_ADMINIST_ZONE_CODE_01) as UPPER_ADMINIST_ZONE_NM_01
    , a.*
from (
select
    COMTCADMINISTCODE.ADMINIST_ZONE_SE /* 青沥内靛.青沥备开备盒 */
    , COMTCADMINISTCODE.ADMINIST_ZONE_CODE /* 青沥内靛.青沥备开内靛 */
    , COMTCADMINISTCODE.USE_AT /* 青沥内靛.荤侩咯何 */
    , COMTCADMINISTCODE.ADMINIST_ZONE_NM /* 青沥内靛.青沥备开疙 */
    , COMTCADMINISTCODE.UPPER_ADMINIST_ZONE_CODE /* 青沥内靛.惑困青沥备开内靛 */
--    , decode(COMTCADMINISTCODE.ADMINIST_ZONE_CODE, '__00000000', COMTCADMINISTCODE.ADMINIST_ZONE_CODE) as UPPER_ADMINIST_ZONE_CODE_01 /* 青沥内靛.青沥备开内靛 */
    , case when COMTCADMINISTCODE.ADMINIST_ZONE_CODE like '__00000000' then '0000000000'
    when COMTCADMINISTCODE.ADMINIST_ZONE_CODE like '_____00000' then substr(COMTCADMINISTCODE.ADMINIST_ZONE_CODE, 1, 2) || '00000000'
    when COMTCADMINISTCODE.ADMINIST_ZONE_CODE like '________00' then substr(COMTCADMINISTCODE.ADMINIST_ZONE_CODE, 1, 5) || '00000'
--    when COMTCADMINISTCODE.ADMINIST_ZONE_CODE like '__________' then substr(COMTCADMINISTCODE.ADMINIST_ZONE_CODE, 1)
    else COMTCADMINISTCODE.ADMINIST_ZONE_CODE
    end as UPPER_ADMINIST_ZONE_CODE_01 /* 青沥内靛.青沥备开内靛 */
    , COMTCADMINISTCODE.CREAT_DE /* 青沥内靛.积己老 */
    , COMTCADMINISTCODE.ABL_DE /* 青沥内靛.企瘤老 */
    , COMTCADMINISTCODE.FRST_REGIST_PNTTM /* 青沥内靛.弥檬殿废矫痢 */
    , COMTCADMINISTCODE.FRST_REGISTER_ID /* 青沥内靛.弥檬殿废磊ID */
    , COMTCADMINISTCODE.LAST_UPDT_PNTTM /* 青沥内靛.弥辆荐沥矫痢 */
    , COMTCADMINISTCODE.LAST_UPDUSR_ID /* 青沥内靛.弥辆荐沥磊ID */
from COMTCADMINISTCODE /* 青沥内靛 */
where 1 = 1
    and COMTCADMINISTCODE.ADMINIST_ZONE_SE = '1' /* 青沥内靛.青沥备开备盒 = 过沥悼 */
--    and COMTCADMINISTCODE.ADMINIST_ZONE_CODE like '__00000000' /* 青沥内靛.青沥备开内靛 矫档 2 */
----    and COMTCADMINISTCODE.ADMINIST_ZONE_CODE like '____000000' /* 青沥内靛.青沥备开内靛 矫焙备 3 */
----    and COMTCADMINISTCODE.ADMINIST_ZONE_CODE like '_______000' /* 青沥内靛.青沥备开内靛 谰搁悼 3 */
----    and COMTCADMINISTCODE.ADMINIST_ZONE_CODE like '__________' /* 青沥内靛.青沥备开内靛 府 2*/
    and COMTCADMINISTCODE.USE_AT = 'Y' /* 青沥内靛.荤侩咯何 */
--order by
--    COMTCADMINISTCODE.ADMINIST_ZONE_CODE /* 青沥内靛.青沥备开内靛 */
) a
where 1= 1
--    and a.UPPER_ADMINIST_ZONE_CODE_01 = '0000000000'
--    and a.UPPER_ADMINIST_ZONE_CODE_01 like '11___00000'
--    and a.UPPER_ADMINIST_ZONE_CODE_01 = '1100000000'
--    and a.UPPER_ADMINIST_ZONE_CODE_01 like '_____00000'
order by
    a.ADMINIST_ZONE_CODE /* 青沥内靛.青沥备开内靛 */
;

select
    level
    , connect_by_root ADMINIST_ZONE_CODE
    , connect_by_root UPPER_ADMINIST_ZONE_CODE_01
    , connect_by_isleaf
    , sys_connect_by_path(ADMINIST_ZONE_CODE, '/')
    , sys_connect_by_path(UPPER_ADMINIST_ZONE_CODE_01, '/')
    , a.*
from (
select
    COMTCADMINISTCODE.ADMINIST_ZONE_SE /* 青沥内靛.青沥备开备盒 */
    , COMTCADMINISTCODE.ADMINIST_ZONE_CODE /* 青沥内靛.青沥备开内靛 */
    , COMTCADMINISTCODE.USE_AT /* 青沥内靛.荤侩咯何 */
    , COMTCADMINISTCODE.ADMINIST_ZONE_NM /* 青沥内靛.青沥备开疙 */
    , COMTCADMINISTCODE.UPPER_ADMINIST_ZONE_CODE /* 青沥内靛.惑困青沥备开内靛 */
--    , decode(COMTCADMINISTCODE.ADMINIST_ZONE_CODE, '__00000000', COMTCADMINISTCODE.ADMINIST_ZONE_CODE) as UPPER_ADMINIST_ZONE_CODE_01 /* 青沥内靛.青沥备开内靛 */
    , case when COMTCADMINISTCODE.ADMINIST_ZONE_CODE like '__00000000' then '0000000000'
    when COMTCADMINISTCODE.ADMINIST_ZONE_CODE like '_____00000' then substr(COMTCADMINISTCODE.ADMINIST_ZONE_CODE, 1, 2) || '00000000'
    when COMTCADMINISTCODE.ADMINIST_ZONE_CODE like '________00' then substr(COMTCADMINISTCODE.ADMINIST_ZONE_CODE, 1, 8) || '00'
--    when COMTCADMINISTCODE.ADMINIST_ZONE_CODE like '__________' then substr(COMTCADMINISTCODE.ADMINIST_ZONE_CODE, 1)
    else COMTCADMINISTCODE.ADMINIST_ZONE_CODE
    end as UPPER_ADMINIST_ZONE_CODE_01 /* 青沥内靛.青沥备开内靛 */
    , COMTCADMINISTCODE.CREAT_DE /* 青沥内靛.积己老 */
    , COMTCADMINISTCODE.ABL_DE /* 青沥内靛.企瘤老 */
    , COMTCADMINISTCODE.FRST_REGIST_PNTTM /* 青沥内靛.弥檬殿废矫痢 */
    , COMTCADMINISTCODE.FRST_REGISTER_ID /* 青沥内靛.弥檬殿废磊ID */
    , COMTCADMINISTCODE.LAST_UPDT_PNTTM /* 青沥内靛.弥辆荐沥矫痢 */
    , COMTCADMINISTCODE.LAST_UPDUSR_ID /* 青沥内靛.弥辆荐沥磊ID */
from COMTCADMINISTCODE /* 青沥内靛 */
where 1 = 1
--    and COMTCADMINISTCODE.ADMINIST_ZONE_SE = '1' /* 青沥内靛.青沥备开备盒 = 过沥悼 */
--    and COMTCADMINISTCODE.ADMINIST_ZONE_CODE like '__00000000' /* 青沥内靛.青沥备开内靛 矫档 2 */
----    and COMTCADMINISTCODE.ADMINIST_ZONE_CODE like '____000000' /* 青沥内靛.青沥备开内靛 矫焙备 3 */
----    and COMTCADMINISTCODE.ADMINIST_ZONE_CODE like '_______000' /* 青沥内靛.青沥备开内靛 谰搁悼 3 */
----    and COMTCADMINISTCODE.ADMINIST_ZONE_CODE like '__________' /* 青沥内靛.青沥备开内靛 府 2*/
--    and COMTCADMINISTCODE.USE_AT = 'Y' /* 青沥内靛.荤侩咯何 */
--order by
--    COMTCADMINISTCODE.ADMINIST_ZONE_CODE /* 青沥内靛.青沥备开内靛 */
) a
START WITH UPPER_ADMINIST_ZONE_CODE = '0000000000'
--START WITH UPPER_ADMINIST_ZONE_CODE_01 = '0000000000'
--START WITH UPPER_ADMINIST_ZONE_CODE_01 = '1100000000'
--START WITH UPPER_ADMINIST_ZONE_CODE = '1100000000'
--START WITH ADMINIST_ZONE_CODE = '1100000000'
--START WITH UPPER_ADMINIST_ZONE_CODE is null
--CONNECT BY PRIOR UPPER_ADMINIST_ZONE_CODE_01 = ADMINIST_ZONE_CODE
--CONNECT BY PRIOR UPPER_ADMINIST_ZONE_CODE = ADMINIST_ZONE_CODE
CONNECT BY PRIOR ADMINIST_ZONE_CODE = UPPER_ADMINIST_ZONE_CODE
--CONNECT BY NOCYCLE PRIOR UPPER_ADMINIST_ZONE_CODE_01 = ADMINIST_ZONE_CODE
ORDER SIBLINGS BY
    ADMINIST_ZONE_CODE
;
