select
    COMTNAUTHORGROUPINFO.*
from COMTNAUTHORGROUPINFO /* 권한그룹정보 */
;

select
    COM_TN_AUTHOR_GROUP_INFO.*
from COMTNAUTHORGROUPINFO COM_TN_AUTHOR_GROUP_INFO /* 권한그룹정보 */
;

select
    /*+ index(AUTHOR_GROUP_INFO COMTNAUTHORGROUPINFO_PK) */
    AUTHOR_GROUP_INFO.*
from COMTNAUTHORGROUPINFO AUTHOR_GROUP_INFO /* 권한그룹정보 */
;
